#!/usr/bin/env node
// Copyright © 2026 Gabriel Worm
// SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0
// Source: https://github.com/ntworm/rc-surface

/**
 * Builds the parts of the published site that search engines and AI crawlers
 * read, from the sources a person edits:
 *
 *   docs/index.html   the <head> block between the seo markers (title,
 *                     description, hreflang, Open Graph, JSON-LD)
 *   docs/pt-br.html   the Portuguese landing page as its own URL, with every
 *                     catalog string already in the markup
 *   docs/llms-full.txt the English README and reference docs in one file
 *   docs/sitemap.xml  both landing URLs with their hreflang pairing
 *
 * The landing page translates itself in the browser, which is enough for a
 * reader and not enough for a search engine: it indexes one URL per language,
 * and a crawler that does not click the PT button never sees Portuguese.
 *
 *   node scripts/build-site.mjs          write the files
 *   node scripts/build-site.mjs --check  exit 1 if any of them is stale
 */
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';

const root = path.resolve(import.meta.dirname, '..');
const docs = path.join(root, 'docs');
const SITE = 'https://ntworm.github.io/rc-surface/';
const PT_FILE = 'pt-br.html';
const REPO = 'https://github.com/ntworm/rc-surface';
const SEO_BEGIN = '<!-- seo:begin — generated by scripts/build-site.mjs, edit it there -->';
const SEO_END = '<!-- seo:end -->';

const version = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')).version;

const META = {
  en: {
    htmlLang: 'en',
    ogLocale: 'en_US',
    url: SITE,
    title: "RC Surface — Ableton Live controller in your phone's browser",
    description: "Turn your phone's browser into a wireless Ableton Live 12 controller: pads, XY, knobs, faders, motion sensors, audio and hand tracking. No app. Free, source-available.",
    ogTitle: 'RC Surface — your phone as an Ableton Live controller',
    imageAlt: 'RC Surface — phone-based controller surface for Ableton Live. Source-available under PolyForm Noncommercial 1.0.0.',
    features: [
      'Twelve performance pads with four modes (momentary, hold, toggle, burst)',
      'Two XY pads, one with physics',
      'Eight knobs and eight faders for the mixer',
      'Four LFOs and four stutters locked to the Live tempo',
      'Eight snapshots with timed and vector morph',
      'Motion and orientation sensors as mapping sources',
      'Twelve audio descriptors from the phone microphone or an audio interface',
      'Single-hand camera tracking with MediaPipe, working offline',
      'Map any control to a Live parameter or a MIDI note from the phone',
      'Local network only: no app on the phone, no cloud, no telemetry',
    ],
  },
  'pt-BR': {
    htmlLang: 'pt-BR',
    ogLocale: 'pt_BR',
    url: SITE + PT_FILE,
    title: 'RC Surface — controle o Ableton Live pelo navegador do celular',
    description: 'Use o navegador do celular como controlador sem fio do Ableton Live 12: pads, XY, knobs, faders, sensores, áudio e rastreio de mãos. Sem instalar app, e grátis.',
    ogTitle: 'RC Surface — o celular como controlador do Ableton Live',
    imageAlt: 'RC Surface — superfície de controle no celular para o Ableton Live. Código-fonte disponível sob a PolyForm Noncommercial 1.0.0.',
    features: [
      'Doze pads de performance com quatro modos (momentâneo, hold, toggle, burst)',
      'Dois XY pads, um deles com física',
      'Oito knobs e oito faders para o mixer',
      'Quatro LFOs e quatro stutters travados no andamento do Live',
      'Oito snapshots com morph por tempo e morph vetorial',
      'Sensores de movimento e orientação como fontes de mapeamento',
      'Doze descritores de áudio do microfone do celular ou de uma interface de áudio',
      'Rastreio de uma mão pela câmera com MediaPipe, funcionando offline',
      'Mapeie qualquer controle para um parâmetro do Live ou uma nota MIDI pelo celular',
      'Só rede local: nenhum app no celular, sem nuvem, sem telemetria',
    ],
  },
};

// ── catalog ────────────────────────────────────────────────────────────────

function loadCatalog() {
  const scope = {};
  vm.runInNewContext(fs.readFileSync(path.join(docs, 'site-i18n.js'), 'utf8'), { globalThis: scope });
  return scope.RcSurfaceSiteCatalog;
}

const escapeText = (value) => String(value)
  .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
const escapeAttr = (value) => escapeText(value).replace(/"/g, '&quot;');

// ── HTML: apply the catalog the way i18n.js does, but ahead of time ────────

const VOID = new Set(['area', 'base', 'br', 'col', 'embed', 'hr', 'img', 'input', 'link',
  'meta', 'source', 'track', 'wbr']);
const RAW = new Set(['script', 'style']);
const ATTRIBUTE_HANDLES = [
  ['data-i18n-title', 'title'],
  ['data-i18n-placeholder', 'placeholder'],
  ['data-i18n-aria-label', 'aria-label'],
  ['data-i18n-href', 'href'],
];

function attr(attrs, name) {
  const m = attrs.match(new RegExp(`\\s${name}="([^"]*)"`));
  return m ? m[1] : null;
}

function setAttr(tag, name, value) {
  const re = new RegExp(`(\\s${name}=")[^"]*(")`);
  if (re.test(tag)) return tag.replace(re, (whole, a, b) => a + escapeAttr(value) + b);
  return tag.replace(/(\s*\/?>)$/, ` ${name}="${escapeAttr(value)}"$1`);
}

/**
 * i18n.js sets textContent for data-i18n and innerHTML for data-i18n-html.
 * An outer replacement discards whatever it contained, so only the outermost
 * handled element of any subtree is rewritten here — the same result the
 * browser reaches.
 */
function translateHtml(html, catalog, locale) {
  const bodyAt = html.indexOf('<body');
  const token = /<!--[\s\S]*?-->|<(\/?)([a-zA-Z][\w-]*)((?:"[^"]*"|'[^']*'|[^>"'])*)>/g;
  token.lastIndex = bodyAt;
  const stack = [];
  const inner = [];   // [start, end, replacement]
  const tags = [];    // [start, end, replacement] for attribute handles
  let m;
  while ((m = token.exec(html))) {
    if (m[0].startsWith('<!--')) continue;
    const closing = m[1] === '/';
    const name = m[2].toLowerCase();
    const attrs = m[3];
    if (closing) {
      for (let i = stack.length - 1; i >= 0; i--) {
        if (stack[i].name !== name) continue;
        const open = stack.splice(i)[0];
        if (open.handle) inner.push([open.contentStart, m.index, open.handle]);
        break;
      }
      continue;
    }
    const selfClosing = /\/\s*$/.test(attrs) || VOID.has(name);
    let tagText = m[0];
    for (const [handle, target] of ATTRIBUTE_HANDLES) {
      const key = attr(attrs, handle);
      const value = key && catalog[key]?.[locale];
      if (value) tagText = setAttr(tagText, target, value);
    }
    if (tagText !== m[0]) tags.push([m.index, m.index + m[0].length, tagText]);
    if (RAW.has(name)) {
      const end = html.indexOf(`</${name}>`, token.lastIndex);
      token.lastIndex = end < 0 ? html.length : end + name.length + 3;
      continue;
    }
    if (selfClosing) continue;
    const textKey = attr(attrs, 'data-i18n');
    const htmlKey = attr(attrs, 'data-i18n-html');
    let handle = null;
    if (htmlKey && catalog[htmlKey]?.[locale] != null) handle = catalog[htmlKey][locale];
    else if (textKey && catalog[textKey]?.[locale] != null) handle = escapeText(catalog[textKey][locale]);
    stack.push({ name, contentStart: token.lastIndex, handle });
  }
  const within = (range, other) => other !== range && other[0] <= range[0] && range[1] <= other[1];
  const edits = [
    ...inner.filter((range) => !inner.some((other) => within(range, other))),
    ...tags.filter((range) => !inner.some((other) => other[0] <= range[0] && range[1] <= other[1])),
  ].sort((a, b) => b[0] - a[0]);
  let out = html;
  for (const [start, end, replacement] of edits) out = out.slice(0, start) + replacement + out.slice(end);
  return out;
}

// ── the <head> block ───────────────────────────────────────────────────────

const stripTags = (value) => value.replace(/<[^>]+>/g, '')
  .replace(/&amp;/g, '&').replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&quot;/g, '"')
  .replace(/&#(\d+);/g, (w, n) => String.fromCodePoint(Number(n)))
  .replace(/\s+/g, ' ').trim();

/** The FAQ as the page shows it in that language, so the markup never promises an answer the page does not give. */
function faqFrom(html) {
  const start = html.indexOf('id="faq"');
  const end = html.indexOf('id="docs"', start);
  const block = html.slice(start, end);
  return [...block.matchAll(/<h4[^>]*>([\s\S]*?)<\/h4>\s*<p class="lead"[^>]*>([\s\S]*?)<\/p>/g)]
    .map((m) => ({ question: stripTags(m[1]), answer: stripTags(m[2]) }));
}

function seoBlock(locale, html) {
  const meta = META[locale];
  const other = locale === 'en' ? META['pt-BR'] : META.en;
  const graph = [
    {
      '@type': 'SoftwareApplication',
      '@id': SITE + '#software',
      name: 'RC Surface',
      alternateName: 'RC Surface for Ableton Live',
      description: meta.description,
      url: meta.url,
      applicationCategory: 'MultimediaApplication',
      applicationSubCategory: 'Ableton Live extension',
      operatingSystem: 'Windows 10/11, macOS; phone: iOS 15.4+ Safari, Android Chromium',
      softwareRequirements: 'Ableton Live 12.4.5+ Suite with Extensions SDK support',
      softwareVersion: version,
      downloadUrl: REPO + '/releases/latest',
      license: 'https://polyformproject.org/licenses/noncommercial/1.0.0/',
      isAccessibleForFree: true,
      offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
      inLanguage: ['en', 'pt-BR'],
      image: SITE + 'og-image.png',
      screenshot: SITE + 'og-image.png',
      featureList: meta.features,
      author: { '@type': 'Person', name: 'Gabriel Worm', url: 'https://ntworm.github.io/', sameAs: ['https://github.com/ntworm'] },
      sameAs: [REPO],
    },
    {
      '@type': 'SoftwareSourceCode',
      '@id': REPO + '#code',
      name: 'RC Surface',
      codeRepository: REPO,
      programmingLanguage: ['TypeScript', 'JavaScript'],
      runtimePlatform: 'Ableton Live Extensions SDK',
      license: 'https://polyformproject.org/licenses/noncommercial/1.0.0/',
      targetProduct: { '@id': SITE + '#software' },
    },
    {
      '@type': 'WebPage',
      '@id': meta.url,
      url: meta.url,
      name: meta.title,
      description: meta.description,
      inLanguage: meta.htmlLang,
      about: { '@id': SITE + '#software' },
      isPartOf: { '@type': 'WebSite', name: 'RC Surface', url: SITE },
    },
    {
      '@type': 'FAQPage',
      '@id': meta.url + '#faq',
      inLanguage: meta.htmlLang,
      mainEntity: faqFrom(html).map(({ question, answer }) => ({
        '@type': 'Question',
        name: question,
        acceptedAnswer: { '@type': 'Answer', text: answer },
      })),
    },
  ];
  const jsonLd = JSON.stringify({ '@context': 'https://schema.org', '@graph': graph }, null, 1)
    .replace(/</g, '\\u003c');
  return [
    SEO_BEGIN,
    `<title>${escapeText(meta.title)}</title>`,
    `<meta name="description" content="${escapeAttr(meta.description)}">`,
    `<meta name="author" content="Gabriel Worm">`,
    `<link rel="canonical" href="${meta.url}">`,
    `<link rel="alternate" hreflang="en" href="${META.en.url}">`,
    `<link rel="alternate" hreflang="pt-BR" href="${META['pt-BR'].url}">`,
    `<link rel="alternate" hreflang="x-default" href="${META.en.url}">`,
    '<link rel="sitemap" type="application/xml" href="sitemap.xml">',
    '<meta property="og:type" content="website">',
    '<meta property="og:site_name" content="RC Surface">',
    `<meta property="og:title" content="${escapeAttr(meta.ogTitle)}">`,
    `<meta property="og:description" content="${escapeAttr(meta.description)}">`,
    `<meta property="og:url" content="${meta.url}">`,
    `<meta property="og:image" content="${SITE}og-image.png">`,
    '<meta property="og:image:width" content="1200">',
    '<meta property="og:image:height" content="630">',
    `<meta property="og:image:alt" content="${escapeAttr(meta.imageAlt)}">`,
    `<meta property="og:locale" content="${meta.ogLocale}">`,
    `<meta property="og:locale:alternate" content="${other.ogLocale}">`,
    '<meta name="twitter:card" content="summary_large_image">',
    `<meta name="twitter:title" content="${escapeAttr(meta.ogTitle)}">`,
    `<meta name="twitter:description" content="${escapeAttr(meta.description)}">`,
    `<meta name="twitter:image" content="${SITE}og-image.png">`,
    `<meta name="twitter:image:alt" content="${escapeAttr(meta.imageAlt)}">`,
    `<script type="application/ld+json">\n${jsonLd}\n</script>`,
    SEO_END,
  ].join('\n');
}

function replaceSeo(html, block) {
  const start = html.indexOf(SEO_BEGIN);
  const end = html.indexOf(SEO_END);
  if (start < 0 || end < start) throw new Error('docs/index.html has lost its seo:begin / seo:end markers');
  return html.slice(0, start) + block + html.slice(end + SEO_END.length);
}

// ── llms-full.txt ──────────────────────────────────────────────────────────

const LLMS_SOURCES = ['README.md', 'docs/INSTALL.md', 'docs/USER-GUIDE.md', 'docs/FAQ.md',
  'docs/CUSTOMIZATION.md', 'docs/COMPATIBILITY.md', 'docs/SECURITY.md', 'docs/PRIVACY.md',
  'docs/CONTRACTS.md'];

function llmsFull() {
  const parts = [
    '# RC Surface — full documentation (English)',
    '',
    '> RC Surface is a free, source-available Ableton Live 12.4.5+ Suite extension that turns a phone',
    '> browser into a wireless controller: pads, XY pads, knobs, faders, LFOs, stutters, snapshots,',
    '> motion sensors, twelve audio descriptors and single-hand camera tracking, mapped to Live',
    '> parameters or MIDI notes over the local network. No app on the phone.',
    '',
    `Version ${version}. Landing page: ${SITE} (Portuguese: ${SITE}${PT_FILE}).`,
    `Source and releases: ${REPO}. Licence: PolyForm Noncommercial 1.0.0.`,
    'Every document below also exists in Brazilian Portuguese beside it, as NAME.pt-BR.md.',
    'Independent project, not affiliated with Ableton AG. Generated by scripts/build-site.mjs.',
  ];
  for (const rel of LLMS_SOURCES) {
    const text = fs.readFileSync(path.join(root, rel), 'utf8').replace(/\r\n/g, '\n').trim();
    parts.push('', '---', '', `<!-- source: ${REPO}/blob/main/${rel} -->`, '', text);
  }
  return parts.join('\n') + '\n';
}

// ── sitemap.xml ────────────────────────────────────────────────────────────

function sitemap() {
  const alternates = [['en', META.en.url], ['pt-BR', META['pt-BR'].url], ['x-default', META.en.url]]
    .map(([lang, href]) => `    <xhtml:link rel="alternate" hreflang="${lang}" href="${href}"/>`)
    .join('\n');
  const urls = [META.en.url, META['pt-BR'].url]
    .map((loc) => `  <url>\n    <loc>${loc}</loc>\n${alternates}\n  </url>`)
    .join('\n');
  return '<?xml version="1.0" encoding="UTF-8"?>\n'
    + '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:xhtml="http://www.w3.org/1999/xhtml">\n'
    + urls + '\n</urlset>\n';
}

// ── main ───────────────────────────────────────────────────────────────────

export function buildSite() {
  const catalog = loadCatalog();
  const source = fs.readFileSync(path.join(docs, 'index.html'), 'utf8');
  // The FAQ in the English block is read from what the English catalog puts
  // on screen, not from the markup's fallback text.
  const en = replaceSeo(source, seoBlock('en', translateHtml(source, catalog, 'en')));

  let pt = translateHtml(en, catalog, 'pt-BR');
  pt = replaceSeo(pt, seoBlock('pt-BR', pt));
  pt = pt.replace('<html lang="en">', '<html lang="pt-BR" data-default-locale="pt-BR">');
  if (!pt.includes('data-default-locale="pt-BR"')) throw new Error('docs/index.html must open with <html lang="en">');

  return {
    'docs/index.html': en,
    ['docs/' + PT_FILE]: pt,
    'docs/llms-full.txt': llmsFull(),
    'docs/sitemap.xml': sitemap(),
  };
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(import.meta.filename)) {
  const check = process.argv.includes('--check');
  const stale = [];
  for (const [rel, content] of Object.entries(buildSite())) {
    const file = path.join(root, rel);
    const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
    if (current === content) continue;
    stale.push(rel);
    if (!check) fs.writeFileSync(file, content);
  }
  if (check && stale.length) {
    console.error(`stale: ${stale.join(', ')} — run npm run build:site`);
    process.exit(1);
  }
  console.log(stale.length ? `${check ? 'stale' : 'wrote'}: ${stale.join(', ')}` : 'site files up to date');
}
